### ISSUE TITLE
Example script?

### ISSUE THREAD

**Issue by st0le** [JerwuQu/wblocks2#1]
This seems very interesting. Do you mind adding any example scripts?

**Comment by JerwuQu** [comment]
It lacks a bit of documentation because it's still not very polished. YMMV.

The most basic script would be something like this as a `.js` file in a `blocks` directory:
```js
const myBlock = createBlock();
myBlock.setFont('Arial', 30);
myBlock.setText('Hello, World!');
```

Which yields:
![image](https://user-images.githubusercontent.com/3710677/187523253-8903b77d-b11f-4e1c-aef7-63c4773396b7.png)

You can use some basic JS features and what's documented in the README.md, but other than that you are on your own.

**Comment by st0le** [comment]
Perfect.
